### ISSUE TITLE
CORS error on link page.

### ISSUE THREAD

**Issue by NotAussie** [cardboard-ink/cardboard#81]
**Describe the bug**
Unable to fetch Guilded accounts when logging in.

**To Reproduce**

1. Go to Login
2. Write anything in the "Guilded Username" box
4. See error (Guilded API returns CORS error)

**Expected behavior**
A list of users is returned.

**Screenshots**

**Desktop:**

- OS: Windows 10 Pro Education
- Browser: Zen (1.0.1-a.12) *(Firefox 131)*
- Version: ? (This question has no context on what it refers to... please just ask if needed)

**Additional context**

**Comment by sosweetham** [comment]
Ye known issue, need to fix.. would have to prolly shift the endpoint to server sideor deprecate if guilded rate limit bugs me :P 

Still havent been able to decide what i should do lol

**Comment by NotAussie** [comment]
You could move it to the server and add caching for results, best of both worlds. (Oh, and you could add a rate limit and possibly make it so it'll only request to the server after the user has stopped writing for a second)
